version: '3.8'

services:
  # 1. AI 분석 서버
  ai-server:
    build: 
      context: ./ai-server   # 방금 만든 ai-server 폴더를 바라봄
    ports:
      - "8000:8000"          # 내 컴퓨터의 8000번과 도커의 8000번 연결
    networks:
      - laundry-network

  # 2. 메인 백엔드 서버
  main-server:
    build: 
      context: ./node-server # 방금 만든 node-server 폴더를 바라봄
    ports:
      - "3000:3000"          # 내 컴퓨터의 3000번과 도커의 3000번 연결
    networks:
      - laundry-network
    depends_on:
      - ai-server            # AI 서버가 먼저 켜진 후에 실행되도록 순서 보장

# 두 서버가 소통할 가상의 네트워크 공간
networks:
  laundry-network:
    driver: bridge